name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout mobile-native-android
      uses: actions/checkout@v3
      with:
        repository: iTwin/mobile-native-android
        ref: '3.2.3'
        token: ${{ secrets.GH_PAT }} # `GH_PAT` is a secret that contains your PAT
        path: mobile-native-android

    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Deploy mobile-native-android to maven local
      run: |
        cd mobile-native-android
        gh release download 3.2.3 -p '*.aar'
        chmod +x gradlew
        ./gradlew publishToMavenLocal
        cd ..
      env:
        GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        
    - name: Checkout mobile-sdk-android
      uses: actions/checkout@v3
      with:
        path: mobile-sdk-android

    - name: Build mobile-sdk-android
      run: |
        cd mobile-sdk-android
        chmod +x gradlew
        ./gradlew build
